// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3_fRo0S2kSKc1wZZRaaeiy0duxChr7es',
    appId: '1:285693378488:android:8717764dbf41a6c3b1594d',
    messagingSenderId: '285693378488',
    projectId: 'myuni-fe6d1',
    storageBucket: 'myuni-fe6d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX33LDGggXv13buKqDydbFzd7aYJKBjK8',
    appId: '1:285693378488:ios:c3b7d446d1975162b1594d',
    messagingSenderId: '285693378488',
    projectId: 'myuni-fe6d1',
    storageBucket: 'myuni-fe6d1.firebasestorage.app',
    iosBundleId: 'com.example.myUni',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtCCv0ZOZCNuwicrNTwU31--OQ1MY2UPg',
    appId: '1:285693378488:web:10e1bb36ada0472eb1594d',
    messagingSenderId: '285693378488',
    projectId: 'myuni-fe6d1',
    authDomain: 'myuni-fe6d1.firebaseapp.com',
    storageBucket: 'myuni-fe6d1.firebasestorage.app',
    measurementId: 'G-RFVD3VFE3W',
  );

}